export const GETLANDEDORIGIN = 'GETLANDEDORIGIN';

export const TYPHOONLIST = 'TYPHOONLIST';

export const LANDEDCLUSTER = 'LANDEDCLUSTER';

export const ORIGINCLUSTER = 'ORIGINCLUSTER';

export const LANDEDTRACK = 'LANDEDTRACK';
